# .pre-commit-config.yaml

repos:

# isort
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]

      
# black
- repo: https://github.com/ambv/black
  rev: 23.1.0
  hooks:
    - id: black
      args: # arguments to configure black
        - --line-length=88
        - --include='\.pyi?$'

        # these folders wont be formatted by black
        - --exclude="""\.git |
          \.__pycache__|
          \.hg|
          \.mypy_cache|
          \.tox|
          \.venv|
          _build|
          buck-out|
          build|
          dist"""

      language_version: python3.9


# flake8
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      args: # arguments to configure flake8
        # making isort line length compatible with black
        - "--max-line-length=88"
        - "--max-complexity=18"
        - "--select=B,C,E,F,W,T4,B9"

        # these are errors that will be ignored by flake8
        # check out their meaning here
        # https://flake8.pycqa.org/en/latest/user/error-codes.html
        - "--ignore=E203,E266,E501,W503,F403,F401,E402,F541"

# mypy; checks for static typing
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.1.1
  hooks:
    - id: mypy
      args: [--ignore-missing-imports]


# interrogate; checks docstring coverage
- repo: https://github.com/econchick/interrogate
  rev: 1.5.0  
  hooks:
    - id: interrogate
      args: [-vv, --fail-under=95]
      exclude: ^(setup.py|test)

# darglint; checks docstring format and content
-   repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
    - id: darglint

- repo: local
  hooks:
    # coverage; tests pytest coverage
    - id: coverage
      name: coverage
      stages: [commit]
      language: system
      entry: coverage run -m pytest
      types: [python]
      pass_filenames: false
      always_run: true
    # pylint; static code analyzer
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      exclude: "setup.py|^tests/"

